export const REASON_TEXT: Record<string, string> = {
  HARD_SESSION_YESTERDAY: "Yesterday was a hard session",
  CONSECUTIVE_HARD_DAYS: "Two or more hard days in a row",
  NO_REST_DAY_RECENTLY: "No rest day in about a week",
  SHORT_SLEEP: "Sleep was under six hours",
  ELEVATED_RESTING_HR: "Resting heart rate is above your baseline",
  WELL_RESTED: "Recovery looks good",
  BEHIND_WEEKLY_TARGET: "Behind on this week's sessions",
  ON_TRACK_WEEKLY_TARGET: "On track this week",
  WEEKLY_TARGET_MET: "This week's sessions are done",
  NO_TRAINING_WINDOW: "No free slot long enough today",
  TIGHT_TRAINING_WINDOW: "Only a short free slot today",
  TRAINING_WINDOW_FOUND: "There is a good slot today",
  HEAVY_MEETING_DAY: "Six or more hours of meetings",
  TRAVEL_DAY: "Travelling today",
  FUEL_FOR_TRAINING: "Today's session needs fuel",
  REFUEL_AFTER_HARD_SESSION: "Yesterday's effort needs refuelling",
  STRENGTH_DAY_PROTEIN: "Strength day: protein first",
  LOW_MOVEMENT_DAY: "A desk-bound day",
  DEFAULT_STEADY: "An ordinary day",
  FIRST_DAY_BACK: "First day back after a break",
  RAIL_MAX_CONSECUTIVE_HARD: "Limit: two hard days is the cap",
  RAIL_MIN_REST_PER_WEEK: "Limit: a rest day every week",
  RAIL_NO_HARD_AFTER_SHORT_SLEEP: "Limit: no hard sessions on short sleep",
  RAIL_NO_LIGHTER_FOOD_AFTER_HARD: "Limit: never lighter food after a hard day",
  RAIL_NO_LIGHTER_FOOD_ON_TRAINING_DAY: "Limit: never lighter food on a training day",
};
